/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.views;

import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidad.controllers.AlumnoData;
import universidad.controllers.Conexion;
import universidad.controllers.MateriaData;
import universidad.models.Alumno;
import universidad.models.Materia;
import universidad.views.GestionInscripcion;

/**
 *
 * @author leo_t
 */
public class Home extends javax.swing.JFrame {

    public static GestionarAlumno formAlumno;
    public GestionInscripcion ins;

    public Home() throws IOException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        Conexion.getConnection();
        String titulo = "Grupo 15 C1";
        String mensaje = "<html>"
                + "<div style='text-align: center;'><h2>Sistema Gestion Alumnos</h2></div>"
                + "<div style='text-align: center;'><h4>Conectar a base datos</h4></div>"
                + "</html>";
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
        Conexion.getConnection();
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/universidad/img/graduacion.png")); // linea para accerder al recurso
        this.setTitle("Home");
        this.setIconImage(icono); //linea para setear un icono al programa
        mostrarTodosAlumnos();

        mostrarTodasMaterias();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane4 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumnos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuMaterias = new javax.swing.JMenu();
        MenuIncripcion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setName("Home"); // NOI18N
        setResizable(false);

        tablaMaterias.setAutoCreateRowSorter(true);
        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaMaterias);

        jTabbedPane1.addTab("Ver todas las Materias", jScrollPane3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jTabbedPane1.addTab("Inscripciones", jScrollPane2);

        tablaAlumnos.setAutoCreateRowSorter(true);
        tablaAlumnos.setBackground(new java.awt.Color(204, 204, 204));
        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tablaAlumnos.setToolTipText("");
        tablaAlumnos.setCellSelectionEnabled(true);
        tablaAlumnos.setGridColor(new java.awt.Color(102, 102, 102));
        tablaAlumnos.setOpaque(false);
        tablaAlumnos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tablaAlumnos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaAlumnos.getTableHeader().setReorderingAllowed(false);
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumnos);

        jTabbedPane1.addTab("Ver todos los Alumnos", jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        Titulo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Sistema de Gestión");
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Universidad de La Punta", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", 2, 14))); // NOI18N

        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(Titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuAlumnos.setText("Alumnos");

        jMenuItem4.setText("Gestionar Alumnos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuAlumnos.add(jMenuItem4);

        jMenuBar1.add(MenuAlumnos);

        MenuMaterias.setText("Materias");
        jMenuBar1.add(MenuMaterias);

        MenuIncripcion.setText("Inscripcion");

        jMenuItem1.setText("Gestion de Inscripciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuIncripcion.add(jMenuItem1);

        jMenuBar1.add(MenuIncripcion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (formAlumno == null) {
            formAlumno = new GestionarAlumno();
            formAlumno.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked

    }//GEN-LAST:event_tablaAlumnosMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
        if (ins == null) {
            ins = new GestionInscripcion();
            ins.setVisible(true);
        }
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de gestion\n Accediendo a los datos");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Home().setVisible(true);
            } catch (IOException | SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAlumnos;
    private javax.swing.JMenu MenuIncripcion;
    private javax.swing.JMenu MenuMaterias;
    private javax.swing.JLabel Titulo;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTable tablaMaterias;
    // End of variables declaration//GEN-END:variables

    /**
     * Asi se documenta perrs
     *
     * @throws IOException
     * @throws SQLException
     */
    public final void mostrarTodosAlumnos() throws IOException, SQLException {
        DefaultTableModel modeloAlumno = new DefaultTableModel();
        AlumnoData alumno = new AlumnoData();
        tablaAlumnos.setModel(modeloAlumno);
        ArrayList<Alumno> alumnos = alumno.selectAlumnosTodos(true);
        modeloAlumno.addColumn("DNI");
        modeloAlumno.addColumn("Nombres");
        modeloAlumno.addColumn("Apellido");
        modeloAlumno.addColumn("Fecha de Nacimiento");
        alumnos = alumno.selectAlumnos(0);// si colocas 0  tendras todoslos alumnos
        for (Alumno alumno1 : alumnos) {
            modeloAlumno.addRow(new Object[]{alumno1.getDni(), alumno1.getNombre(), alumno1.getApellido().toUpperCase(), alumno1.getFecha_nacimiento()});
        }
    }

    /**
     *
     * @throws IOException
     * @throws SQLException
     */
    public final void mostrarTodasMaterias() throws IOException, SQLException {
        DefaultTableModel modeloMateria = new DefaultTableModel();
        MateriaData materia = new MateriaData();
        ArrayList<Materia> materias = materia.selectMaterias(0);
        modeloMateria.addColumn("Nombre");
        modeloMateria.addColumn("Año en curso");
        modeloMateria.addColumn("Estado");
        for (Materia materia1 : materias) {
            modeloMateria.addRow(new Object[]{materia1.getNombre(), materia1.getAnio(), materia1.isEstado()});
        }

        tablaMaterias.setModel(modeloMateria);
    }

    public void mostrarTodasInscripciones() throws IOException, SQLException {
        DefaultTableModel modeloInscripcion = new DefaultTableModel();

    }
}
